### ISSUE TITLE
Unexpected end of JSON input while parsing

### ISSUE THREAD

**Issue by ogurinkaben** [bencodezen/vuepress-blog-boilerplate#11]
I keep getting this error whenever I run '**npm install**' after cloning the repo

**Comment by bencodezen** [comment]
@simplytammy Thanks for filing this. I'll look into this today and get back to you!

**Comment by bencodezen** [comment]
@simplytammy Can you send me the error along with which version of npm you're using?

I just ran the project with npm 6.4.1 and it started up correctly.

**Comment by ogurinkaben** [comment]
![This is the error](https://res.cloudinary.com/simplytammy/image/upload/v1546982282/Screenshot_94.png) 
And I use npm 6.4.1

> @simplytammy Can you send me the error along with which version of npm you're using?
> 
> I just ran the project with npm 6.4.1 and it started up correctly.

**Comment by bencodezen** [comment]
@simplytammy I wonder if it's because you're on Windows. I definitely have not tested the installation there. 

Is it starting up properly now?

**Comment by ogurinkaben** [comment]
I just tried it again, same issue

> @simplytammy I wonder if it's because you're on Windows. I definitely have not tested the installation there.
> 
> Is it starting up properly now?

**Comment by bencodezen** [comment]
@simplytammy Sorry I misread the comment. I completely missed the fact it was a quote and not you saying "it started up correctly."

Anyhow, I just tested it on my Windows machine with two settings:

- Node v5.6.0
- Node v10.15.0

I ran npm install and I got the same warning for "Browserlist 2 could fail..." but it installed correctly. Is it possible for it to be a global cache issue or something? The error says something about `..npmjs.org/caniuse-db`

**Comment by ogurinkaben** [comment]
I think it's a global issue cause I also tried starting a new vue project with a template and I got that same error when I ran "npm install". But starting a new project using the "vue create" command ran smoothly. So perhaps it was an issue with npm.

**Comment by ogurinkaben** [comment]
I'll clean npm cache and try again

**Comment by ogurinkaben** [comment]
> I'll clean npm cache and try again

This worked and I have been able to install now

**Comment by bencodezen** [comment]
@simplytammy Whew! Glad to hear it man! 🙌
