### ISSUE TITLE
Get the date from the url of the .md file like Jekyll

### ISSUE THREAD

**Issue by diegologs** [bencodezen/vuepress-blog-boilerplate#18]
Jekyll uses a convention to name the files:

yyyy-mm-dd-slug.md

With this convention the files are sorted in the folder automatically. 
It also takes the date from the url without having to add it inside the file and the slug to generate the url of the file inside the web.

Then, In the BlogPostPreview we will need a variable to display the slug (To create the router link to the post)

If the files could be created this way, many Jekyll users could switch to Vuepress.

**Comment by bencodezen** [comment]
I'm going to close this for now in favor of eventually contributing to the core package rather than a customization on this boilerplate. Marking it with a label so this doesn't get lost. Thanks for the suggestion!
