### ISSUE TITLE
Comment system plugin for VuePress

### ISSUE THREAD

**Issue by ghost** [bencodezen/vuepress-blog-boilerplate#23]
Greetings!.

I'd like a lightweight comment system plugin for VuePress. Check out this one. Thanks

https://comment.sh/
https://www.talkyard.io/

**Comment by klarkc** [comment]
Where should the comments be hosted? Vuepress focus only in client side to be able to run anywhere that runs javascript. Should we write a plugin that POST/GET to an URL and let the dev handle the data on a microservice or third party services?

**Comment by klarkc** [comment]
I have an Idea that envolves github gist service through oauth authentication, but to do that, we should have a service, because a client only solution is not safe :/

**Comment by klarkc** [comment]
Another idea is to store comments in a p2p distributed service like https://gun.eco/, and tell the dev to install and run a tiny server to connect the peers.

**Comment by bencodezen** [comment]
@klarkc Definitely a fair concern. I think comment.sh helps to host it for you if I'm not mistaken, but if not, part of the documentation would definitely need to provide a easy to walk through tutorial for getting something up and running to host the database and manage oauth and such.

**Comment by emsuiko** [comment]
Have you considered disqus yet? https://disqus.com/

**Comment by klarkc** [comment]
I like the disqus idea

**Comment by bencodezen** [comment]
@emsuiko @klarkc Great question! I should address this in the docs:

So Disqus is an easy plug and play commenting system, but I have been told my multiple sources that there is some sketchiness as far as the amount of tracking that goes on with its use? However, it might not be a big deal for most solo bloggers, so to your point, I will add a section for how to get this integrated if tracking is not an issue.

**Comment by bencodezen** [comment]
Closing since this project will no longer be maintained.
