### ISSUE TITLE
Webshop/Donate plugin for VuePress

### ISSUE THREAD

**Issue by ghost** [bencodezen/vuepress-blog-boilerplate#25]
Hello!.

In order to accept donations or to sell my products/info-products on my blog. I need a cryptocurrency plugin for VuePress.

For reference check out:
1. mycryptocheckout.com
2. https://jekyllcodex.org/without-plugin/webshop/
3. https://jekyllcodex.org/donate/

Thanks.

**Comment by bencodezen** [comment]
Closing since this project will no longer be maintained.
