### ISSUE TITLE
Instagram and Twitter Feed

### ISSUE THREAD

**Issue by ghost** [bencodezen/vuepress-blog-boilerplate#26]
Greetings!.

A blog plugin for Instagram and Twitter Feed is needed on VuePress.

For reference:
Instagram: https://jekyllcodex.org/without-plugin/instagram/
Twitter: https://jekyllcodex.org/without-plugin/twitter-feed/

Thanks.

**Comment by bencodezen** [comment]
Closing since this project will no longer be maintained.
