### ISSUE TITLE
Follow and Share Buttons

### ISSUE THREAD

**Issue by ghost** [bencodezen/vuepress-blog-boilerplate#27]
Hi!.

If we could have a plugin for VuePress that allows me to choose from a list, several social media for sharing posts and follow buttons for the blog. So by default it'll has Facebook, Twitter, Linkedin, WhatsApp, Telegram and Email. But through the configuration I'll be able to add more such as: VK, Github, Instagram, Tumblr, Google+, Weibo, etc...

That's would be awesome and headless for non-programmers.
Thanks.

**Comment by bencodezen** [comment]
Closing since this project will no longer be maintained.
