### ISSUE TITLE
SEO. Sitemap. Metrics. Pretty URL's. Breadcrumbs.

### ISSUE THREAD

**Issue by ghost** [bencodezen/vuepress-blog-boilerplate#28]
Hello!.

Check out all this, the main idea is to have all this features in VuePress.

References:
SEO: https://jekyllcodex.org/without-plugin/seo/
Sitemap: https://jekyllcodex.org/without-plugin/sitemap/
Metrics: https://jekyllcodex.org/without-plugin/metrics/
Pretty URL's: https://jekyllcodex.org/without-plugin/pretty-permalinks/
Breadcrumbs: https://jekyllcodex.org/without-plugin/breadcrumbs/

**Comment by bencodezen** [comment]
@zagerduerin I'm going to close this for now, but will keep this in the backlog under a `vuepress-requests` label when the core library is a little more stable and I can contribute these plugins in. Thanks again for compiling these!
