### ISSUE TITLE
Make all config parameters explicit

### ISSUE THREAD

**Issue by Nivek92** [bencodezen/vuepress-blog-boilerplate#31]
Hey, 
I think it would be good to have each configurable parameter explicitly in the themeConfig.
This saves time because one does not have to look through code what parameters can be set.

**Comment by bencodezen** [comment]
@Nivek92 Good suggestion! I was trying not to expose too much at once so that people were not overwhelmed, but I will see what remaining configurations are important for people and document them accordingly so people can use it without referring to the docs

**Comment by bencodezen** [comment]
@Nivek92 I exposed what I thought would be most common at this point, but I hope to eventually merge this guide with the main VuePress docs in order to better centralize doc efforts. Thanks again for filing this issue!
