### ISSUE TITLE
list all posts with specific tag

### ISSUE THREAD

**Issue by emsuiko** [bencodezen/vuepress-blog-boilerplate#41]
Hey Ben,

thanks for sharing this project! 😃 

In the post meta there's a possibility to add tags. As far as I can see those aren't used anywhere otherwise?
I figured out how to display the tags on the post page itself. I'd like to link the tag to a page that lists all posts with that specific tag tho.
I see there's a selectedTags data item in the BlogPostList component. I just couldn't figure out how to use it.

Can you point me in the right direction on how to use the tags? Thanks! 🙂

**Comment by bencodezen** [comment]
@emsuiko Definitely. Let me update the codebase so it utilizes it again. Thanks for creating this issue!

**Comment by bencodezen** [comment]
@emsuiko I just updated the code and the docs. Feel free to reopen the issue or open a new one if you have additional questions!
