### ISSUE TITLE
VuePress Blog out of the Box page layout issue

### ISSUE THREAD

**Issue by ultradox** [bencodezen/vuepress-blog-boilerplate#46]
Hello - I'm following along the [tutorial](https://vuepress-blog-boilerplate.bencodezen.io/learn/#tutorial) but quickly run into trouble.

```
node --version
v11.6.0
npm --version
6.10.1

git clone https://github.com/bencodezen/vuepress-blog-boilerplate.git
cd vuepress-blog-boilerplate
npm install
npm run dev
```

This is what I see:
The Homepage looks as expected:
![1-homepage src--README md](https://user-images.githubusercontent.com/12581775/61447267-b8b34d80-a9a4-11e9-8f26-b026725681eb.jpg)

CSS renders quite different than in ./preview.png included in the repo:
![2-blog src--blog--README md](https://user-images.githubusercontent.com/12581775/61447269-b8b34d80-a9a4-11e9-89d0-2097cd66005b.jpg)

The custom container displays ::: tip [text] ::: 
![4-my-fourth-post](https://user-images.githubusercontent.com/12581775/61447272-b94be400-a9a4-11e9-9507-e212bed7c272.jpg)

Any ideas why this might be the case?

**Comment by bencodezen** [comment]
You're totally right. Something is broken. Let me try and figure out what's going on!

**Comment by bencodezen** [comment]
I'm sad to report that it looks like something is wrong with the `npm install` at the moment. When I run it with `npm`, I can replicate your bug. But with `yarn`, everything works properly. Sorry for the sucky solution. I'm going to be upgrading this in the near future and hopefully that will be fixed properly then. 

Let me know if you have any other questions!

**Comment by ultradox** [comment]
Awesome thanks Ben!!
