### ISSUE TITLE
Missing posts on certain browsers

### ISSUE THREAD

**Issue by kamicrafted** [bencodezen/vuepress-blog-boilerplate#53]
I've run into a strange bug that prevents certain posts from showing up depending on the browser being used. I currently have 3 posts set up and they all show up as expected locally, as well as for Chrome and Firefox. However, for desktop and mobile safari, the second post doesn't show in view or in the DOM. I do notice upon rapid refresh a flicker of the second post which further adds to the mystery.

The site can be tested by going to https://blog.kamicrafted.com/ on Chrome vs Safari.

---

Screenshots of the difference:

Chrome
![image](https://user-images.githubusercontent.com/1197908/68027190-159eef00-fc88-11e9-8e25-50bb8d99f83c.png)

Safari ("Setting up LEMP and HTTPS/SSL on Digital Ocean" is missing)
![image](https://user-images.githubusercontent.com/1197908/68027172-05870f80-fc88-11e9-8716-8e8f395b08b6.png)

**Comment by kamicrafted** [comment]
Figured out what the issue was, looks like I goofed up and didn't have the proper date formatted in the frontmatter.

Changing `date: 2020-01-08 15:22:2` to `date: 2020-01-08 15:22:23` fixed the issue and the missing post is now showing up in Safari.

**Comment by bencodezen** [comment]
@kamicrafted That's no good. While it may be slightly mistaken at some points, I feel like the tool should automatically help avoid these types of issues by at least reporting that the date is malformed. Glad you figured it out though!
