### ISSUE TITLE
Page component layout is broken

### ISSUE THREAD

**Issue by lhsazevedo** [bencodezen/vuepress-blog-boilerplate#54]
The layout is missing max-width and padding. Adding the .content class to the `<Content />` in the `<Page>` component fixes the issue.

Without .content class:
![Before](https://user-images.githubusercontent.com/7695608/68057936-3e4dd580-fcd6-11e9-9311-ce0d0791d326.png)

With:
![After](https://user-images.githubusercontent.com/7695608/68058189-1dd24b00-fcd7-11e9-963b-a0fb77b421d2.png)

**Comment by bencodezen** [comment]
Thanks for opening the issue @lhsazevedo! I plan on doing a major upgrade for the boilerplate with the latest VuePress release. So I'll make sure this is fixed!

**Comment by bencodezen** [comment]
Closing since this project will no longer be maintained.
